# tests/SConstruct

Import('env')
Import('libfoo')

env.Append(CPPPATH='../lib')

test_foo = env.Program('test_foo', ['test_foo.c'],
            LIBS=[libfoo])

Alias('test', env.Command('run_tests', test_foo, './tests/test_foo'))